extends Node3D


@onready var basic_enemy1 : PackedScene = preload("res://Entities/Enemy/abel_teszt/abel.tscn")
@onready var basic_enemy2 : PackedScene = preload("res://Entities/Enemy/Basic enemy test/monger.tscn")
@onready var forest : PackedScene = preload("res://Assets/Models/Environment Models/Foilage/Forests/Lightgreen Forest/lightgreen_forest.tscn")
@onready var markers : Array[Marker3D] = [$"Fight Area/Leave", $"Fight Area/Enter"]

var enemy_num : int = 6

func _ready() -> void:
	await get_tree().create_timer(5).timeout
	Global.stat_tablet.purge_message("We crashed because of the magnetic field which is generated by that big tower")
	Global.stat_tablet.purge_message("However, we might find enough stuff to craft a explosive and a radio")
	Global.stat_tablet.purge_message("So you should **collect things**")
	Global.stat_tablet.purge_message("Hahahahahahahahahhahahahhah, get it?")
	Global.stat_tablet.purge_message("Anyway, Good luck")

func _on_fight_area_3d_body_entered(body: Node3D) -> void:
	$"Fight Area/FightArea3D".queue_free()
	
	for marker : Marker3D in markers:
		var trees : Node3D = forest.instantiate()
		var invis_wall := StaticBody3D.new()
		var coll_shape := CollisionShape3D.new()
		var shape := BoxShape3D.new()
		
		shape.size = Vector3(52, 50, 100)
		
		coll_shape.shape = shape
		
		invis_wall.add_child(coll_shape)
		
		trees.rotate_y(-90)
		
		marker.add_child(trees)
		marker.add_child(invis_wall)
		
	for i in range(0,enemy_num):
		get_tree().create_timer(1*i).timeout.connect(spawn_enemy)
		
	


func spawn_enemy() -> void:
	var enemy : CharacterBody3D = basic_enemy1.instantiate()
	get_tree().current_scene.add_child(enemy)
	enemy.global_position = $"Fight Area/Enemy spawner".global_position
	
	enemy.hitbox_component.health_component.died.connect(check_if_all_enemy_died)
	


func check_if_all_enemy_died() -> void:
	enemy_num -= 1
	
	if enemy_num == 0:
		for marker in markers:
			marker.queue_free()
	
